# SPDX-License-Identifier: GPL-2.0
# Makefile for max serdes/deserdes i2c drivers.
#
CONFIG_DRM_I2C_TI_983=y
ccflags-y +=-DDEBUG
fpd_dp_ser_drv-obj := fpd_dp_ser_drv.o
obj-$(CONFIG_DRM_I2C_TI_983)+=fpd_dp_ser_drv.o
